### ISSUE TITLE
Translate cypher query to ActiveNode

### ISSUE THREAD

**Issue by iehdk** [neo4jrb/activegraph#1523]
How can this cypher expression:

```
MATCH (Scaffold {branch_count: 1, edge_count: 4})-[HAS_MOLECULE]->(m:Molecule {atom_count: 5, formula: 'C2N1O2'}),
(m)-[HAS_ATOM]->(a0:Atom),
(a0:Atom {element: 'C'})-[:HAS_BOND {bond_type: 'single'}]-(a1:Atom {element: 'C'}),
(a0:Atom {element: 'C'})-[:HAS_BOND {bond_type: 'single'}]-(a2:Atom {element: 'O'}),
(a0:Atom {element: 'C'})-[:HAS_BOND {bond_type: 'double'}]-(a3:Atom {element: 'O'}),
(a1:Atom {element: 'C'})-[:HAS_BOND {bond_type: 'single'}]-(a4:Atom {element: 'N'})
RETURN m
```

Be translated to  #ActiveNode?

**Comment by iehdk** [comment]
I do in fact agree that the Cypher version is more readable - and it is way easier to find good help on Cypher queries because of the bigger user group.

I will in fact be constructing queries dynamically, but putting together a cypher string is pretty straight forward. Let me see if I can get this this `ActiveBase.query` to work. (For now it goes `undefined method `pluck' for #<Neo4j::Core::CypherSession::Result:0x00007fe3681ea1b0> (NoMethodError)` for some reason).

Before was testing neo4j-core's `session.query`, but I would like to get ActiveNode objects returned instead of `Neo4j::Core::Node` objects - unless I should go completely neo4j-core (is that recommended?).

**Comment by thefliik** [comment]
Regarding the error you're running into, are you sure neo4jrb is set up properly? I.e. it's connecting to the database, etc.

If you just want to dynamically compose cypher strings, definitely check out neo4j-core. You can get a [neo4j-core query object](https://neo4jrb.readthedocs.io/en/9.2.x/QueryClauseMethods.html) with `Neo4j::ActiveBase.new_query`, and use can use it like

```
query = Neo4j::ActiveBase.new_query

query = query.match("(Scaffold {branch_count: 1, edge_count: 4})-[HAS_MOLECULE]->(m:Molecule {atom_count: 5, formula: 'C2N1O2'})")
     .match("(m)-[HAS_ATOM]->(a0:Atom)")
     .match("(a0:Atom {element: 'C'})-[:HAS_BOND {bond_type: 'single'}]-(a1:Atom {element: 'C'})")
     .match("(a0:Atom {element: 'C'})-[:HAS_BOND {bond_type: 'single'}]-(a2:Atom {element: 'O'})")
     .match("(a0:Atom {element: 'C'})-[:HAS_BOND {bond_type: 'double'}]-(a3:Atom {element: 'O'})")
     
query = query.match("(a1:Atom {element: 'C'})-[:HAS_BOND {bond_type: 'single'}]-(a4:Atom {element: 'N'})")

query.pluck(:m)
```

- [Query clause methods docs](https://neo4jrb.readthedocs.io/en/9.2.x/QueryClauseMethods.html)

The above should return ActiveNode / ActiveRel objects (assuming you've created the models).

One potential "gotcha" with neo4j-core query clause methods is that it will automatically combine clauses. I.e., multiple `.match` calls (like above) are, by default, combined into the same `MATCH` clause with a comma `,`. In this case that's what you want, but if you wanted separate match clauses you'd need to call `.break` on the chain.

I.e. this:

```
query = Neo4j::ActiveBase.new_query

query = query.match("(Scaffold {branch_count: 1, edge_count: 4})-[HAS_MOLECULE]->(m:Molecule {atom_count: 5, formula: 'C2N1O2'})")

query = query.break.match("(m)-[HAS_ATOM]->(a0:Atom)")
```

This leads to
```
MATCH (Scaffold {branch_count: 1, edge_count: 4})-[HAS_MOLECULE]->(m:Molecule {atom_count: 5, formula: 'C2N1O2'})
MATCH (m)-[HAS_ATOM]->(a0:Atom)
```

#### Also:
I just updated the ActiveNode query in my original answer because I hadn't noticed that your query referred to the `a0` node multiple times. Regardless, hopefully you get the idea.

**Comment by thefliik** [comment]
Also, off the top of my head, I don't remember how Neo4jrb translates queries using `.branch`. It may use a `WHERE` clause, which, while ultimately returning the same results as your original cypher query, wouldn't be as performant (I think).

**Comment by iehdk** [comment]
Right. Thanks for the help. I got the `results = Neo4j::ActiveBase.query()` to work (though no pluck-luck, so iterating over the results instead).

**Comment by bobmazanec** [comment]
CodeTriage referred me here.
Seems like this can be closed.
If not, how can I help?

**Comment by amitsuryavanshi** [comment]
Closing this. @iehdk, you can reopen it you still have any issues. Thanks.

**Comment by amitsuryavanshi** [comment]
Thanks @bobmazanec
